### ISSUE TITLE
Have you planned to add the support to PE executables?

### ISSUE THREAD

**Issue by andreafioraldi** [GJDuck/e9patch#1]
Hi,
Instrumenting binaries for coverage in Windows in challenging, but your tehcnique is promising so have you planned to add support for it?
You can use https://github.com/lief-project/LIEF for instance and have the same code to handle ELF, PE, and Mach-O with small modifications.

Regards,
Andrea

**Comment by GJDuck** [comment]
Hi,
PE executables are definitely something we'd like to support.  The main requirements would be:

1. Some way to inject a loader that runs before the normal entry point; and
2. Support for large numbers of file mappings necessary to load the trampolines.

We figured out how to do this for ELF/Linux, but have not studied Windows yet.

**Comment by andreafioraldi** [comment]
With LIEF you can link dynamic libraries to a PE, and IIRC you can also set that its initializer (DllMain) has to be the first to run.
Always with LIEF you can easily add sections to binaries, so maybe you can just have the trampolines in memory and relocate to the right location before start.

**Comment by GJDuck** [comment]
Thanks, I will need to study it.

**Comment by GJDuck** [comment]
@gsuberland Thank you for the very detailed response, I think it will be very helpful.  Most of the steps are similar to what is already implemented for ELF/Linux, basically:

* Inject an extra segment into the binary which contains a loader.  For ELF/Linux this currently uses the well-known `PT_NOTE` trick.  For PE/Windows, it seems there would be enough space to extend the section table.
* Change the entry point so that the loader is executed first.  For ELF/Linux this is tricky since there is are exe/dso cases to consider.  Also, there are some dynamic linker extensions that can call the code before the entry point.  However, this should all be figured out and the current implementation seems stable.  For PE/Windows, I assume the entry point can easily be changed to point to the loader?
* The loader must find the currently executing binary file, so additional data (such as trampolines) can be mapped in.  For ELF/Linux it currently uses the `/proc/` directory to do this.  I think it may also be possible to use the `DYNAMIC` segment for this, provided the binary is dynamically linked, but this is unimplemented.  For Windows, maybe it is possible to use the `PEB` to find the binary path?
* The loader must also make several system calls.  E.g., for ELF/Linux, `open`, `mmap`, etc., are used.  For PE/Windows, the Windows equivalents will need to be used (e.g., `CreateFile`, `MapViewOfFile`, etc.).  However, it is not clear to me how to make these system calls.  Under Linux, the syscall interface is static, so it is not a problem.  Under Windows, it is not static, and it seems the "correct" way to do it is via `kernel32.dll` calls (or even the `ntdll.dll` equivalents).  So how can these dlls and corresponding  functions be found by the loader?
* The loader maps in all the necessary data, then jumps to the original entry point.  For ELF/Linux the main problem is the ` vm.max_map_count` limit.  I am not sure if there are similar limits for PE/Windows.  The `HANDLE` limit of 16M should not be a problem.

To implement this, the `e9elf.cpp` file would need to be generalized or reimplemented for PE executables.  The E9Tool frontend would also need to be extended too.

**Comment by gsuberland** [comment]
Grab a drink, this is a long one.

> Inject an extra segment into the binary which contains a loader. For ELF/Linux this currently uses the well-known PT_NOTE trick. For PE/Windows, it seems there would be enough space to extend the section table.

Yup, or even if you do need to move the sections, you just patch the raw addresses on the section table, since everything inside the sections is referenced by RVA, which is not affected by the raw address (offset in the file).

> Change the entry point so that the loader is executed first. For ELF/Linux this is tricky since there is are exe/dso cases to consider. Also, there are some dynamic linker extensions that can call the code before the entry point. However, this should all be figured out and the current implementation seems stable. For PE/Windows, I assume the entry point can easily be changed to point to the loader?

All you have to do is change the `AddressOfEntryPoint` field in the PE header to point to the RVA of the entry point, which is just the RVA of the new section plus whatever offset the entry point is in that section. So, for example, if you added a new section and gave it an RVA of 0x280000, and the entry point was 0x40 bytes into that section, your `AddressOfEntryPoint` field just gets set to 0x280040.

> The loader must find the currently executing binary file, so additional data (such as trampolines) can be mapped in. For ELF/Linux it currently uses the /proc/ directory to do this. I think it may also be possible to use the DYNAMIC segment for this, provided the binary is dynamically linked, but this is unimplemented. For Windows, maybe it is possible to use the PEB to find the binary path?

You can get the binary path via the PEB. What you do is you search through `PEB->Ldr->InLoadOrderModuleList` for an `LDR_DATA_TABLE_ENTRY` structure that has a `DllBase` field matching `PEB->ImageBaseAddress`. Once you've found that, you can read `FullDllName`. Ignore the fact that these fields mention DLLs - it just means "modules" which can be anything executable, including the main executable.

Another (possibly easier) approach is to just call [`GetModuleFileNameW`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew), which will give you the path of the main module for the process if you pass NULL to the `hModule` parameter.

> The loader must also make several system calls. E.g., for ELF/Linux, open, mmap, etc., are used. For PE/Windows, the Windows equivalents will need to be used (e.g., CreateFile, MapViewOfFile, etc.). However, it is not clear to me how to make these system calls. Under Linux, the syscall interface is static, so it is not a problem. Under Windows, it is not static, and it seems the "correct" way to do it is via kernel32.dll calls (or even the ntdll.dll equivalents). So how can these dlls and corresponding functions be found by the loader?

Probably makes sense for me to explain the whole approach here 'cos it requires some knowledge of PEs. All screenshots here are from CFF Explorer, which is a PE editor tool. It's kinda old but it gets the job done. I'm also just looking at a 64-bit executable since 32-bit structures are slightly different.

PEs files start with an old 16-bit DOS header. This header is almost entirely ignored on modern Windows, so the only fields that typically matter are `e_magic` (which must be 'MZ') and `e_lfanew`, which points to the offset of the NT header.

![image](https://user-images.githubusercontent.com/6430604/129734445-2ec6adcf-58a1-4b2c-b0b1-1b68c74133f6.png)

The `e_lfanew` field is always at 0x3C. It tells you the offset of the NT headers. Here's a tree view of the overall structure just to keep the overall layout in your head.

![image](https://user-images.githubusercontent.com/6430604/129734738-7cd9084c-60e2-428e-af1b-708f66670434.png)

The [NT header](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_nt_headers64) only actually has one field of its own, which is Signature. This is a 32-bit field set to `PE\0\0`, i.e. 0x004550.

![image](https://user-images.githubusercontent.com/6430604/129734887-2c03293c-c9da-4aaf-ad7d-bf4f991c06a3.png)

You can see that its offset is at 0x108, which is where `e_lfanew` said it was. You might notice that there's a bit of a gap between the end of the PE header at 0x40 and the start of the NT header at 0x108.

What sits in that space is the DOS stub. You know the old "This program cannot be run in DOS mode"? That's actually a 16-bit x86 DOS program, stored in the file immediately after the `e_lfanew` field, but before the NT header. If you try to run a modern Windows PE under DOS, it runs that program instead of the PE. Since the `e_lfanew` field is 32-bit, you can actually embed a complete 16-bit DOS program in there for cross-compatibility!

For fun, here's the stub disassembled:

![image](https://user-images.githubusercontent.com/6430604/129737386-c14db669-d662-4d9c-86dd-f4a0b544ed9e.png)

If you're really eagle-eyed, you might have noticed that the DOS header plus the string it references still doesn't make up the full size of the gap between 0x40 and 0x108. And you'd be right. This executable also happens to contain something called a [RICH header](https://bytepointer.com/articles/the_microsoft_rich_header.htm), which is a kinda weird self-contained debug blob. Has its uses, but irrelevant here.

Anyway, back to the main topic. After the NT header signature comes the [File Header](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_file_header) and the [Optional Header](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header64). These are sequential.

The File Header contains some important fields.

![image](https://user-images.githubusercontent.com/6430604/129738878-9c68430b-c7c2-43c1-be64-2aac61aa8f62.png)

The first is the `Machine` field, which tells you what machine this was built for. 0x8664 means x86_64, and 0x14C means x86_32. There are a bunch more defined values but unless you're planning on working with Itanium or ARM PEs I wouldn't worry about it.

Next is the `NumberOfSections` field. This tells you how many sections there are in the section table. We'll come to that later.

TimeDateStamp and the symbol table fields can be ignored. `SizeOfOptionalHeader` is the next of importance - it tells us how big the next structure is going to be. It should always be `0xF0` on a 64-bit executable.

Finally there's `Characteristics`. This is a bitfield that specifies various flags. The flags in here should be irrelevant for your use-case, but flag 0x20 is "image can handle >2GB address space" which, if you ever do 32-bit stuff, will be important because it signifies PAE compatibility, i.e. the ability to have a virtual address space up to 3GB (or sometimes 4GB) in size per 32-bit process. If you're just doing 64-bit, ignore this.

The optional header is where most of the magic happens. It's different between 32-bit and 64-bit programs. I'll focus only on 64-bit. 

![image](https://user-images.githubusercontent.com/6430604/129740242-1258be05-08ac-45c0-87bb-9fd2117eadbf.png)

The first field here tells you which structure to use. 0x020B is PE64, 0x010B is PE32.

The `SizeOfCode` and `SizeOfInitializedData` fields are the sum of the sizes of the sections that have the "Contains code" and "Contains initialised data" flags respectively. You shouldn't need to update these since if you inject a new section you don't actually have to apply these flags to make it work. I'll get into that later.

`AddressOfEntryPoint` is the RVA of the entry point. Notice that CFF has marked it as ".text" next to it, indicating that this RVA points to something in the .text section. This field is what you change to make the PE start executing your own stub.

`BaseOfCode` is the RVA of the code section. You shouldn't need to touch this, but it basically just points to the virtual address of the .text section.

`ImageBase` is the "preferred" base address of the executable, i.e. if ASLR was disabled the image would be loaded at that virtual address assuming that nothing else was already loaded there. This is largely irrelevant these days, although it does have one weird implementation detail - in order to support full "high entropy" ASLR the specified image base must be in the upper side of the 64-bit virtual address space, i.e. 0x100000000 or higher. You can generally ignore this.

`SectionAlignment` is the alignment of the virtual address space for sections. This is usually set to 0x1000, i.e. one page. You are not allowed to specify section start addresses or sizes with smaller granularities than the alignment. So all sections' virtual addresses must start at a multiple of 0x1000.

`FileAlignment` is the alignment of the section data in the file. Each section has a "Raw Address" and "Raw Size" field that specifies where its contents are in the PE file. This is how the loader takes code and data from the PE file and puts it in memory ready to be used. The `FileAlignment` field must be at least 0x200 on Win10, and it is usually 0x200 anyway. This means that the data for each section in the file must start at an offset that is a multiple of the file alignment, and its size must also be a multiple of the file alignment. Don't worry if this is a bit confusing, you'll see this more clearly later.

`SizeOfImage` is supposed to be the size of the image, but it's calculated in a weird way. Basically take the highest virtual address of a section, add the virtual size, and round up to a multiple of `SectionAlignment`. Here it's 0x2BF000 + 0xA7D7C = 0x366D7C, which gets you 0x367000. You'll need to update this if you inject a new section.

`SizeOfHeaders` is the size of all image headers rounded up to `FileAlignment`. Almost always 0x400 in normal executables, but may be 0x200 in packed executables that omit some data directories and have only one section.

`CheckSum` is generally ignored. Technically if it is set it to a non-zero value it should be correct, but in practice it doesn't matter. Good practice to zero it or set it correctly if you're modifying a PE, but not strictly necessary.

`Subsystem` tells you which subsystem loads the PE. The two you'll run into are 0x0002, which is Windows GUI, and 0x0003, which is Windows Console. You might also see 0x0001, which is Native, i.e. a kernel driver.

`DllCharacteristics` tells you a bunch of flags about the executable. 0x40 is dynamic base (ASLR supported), 0x80 is the force integrity flag (related to signing policies), 0x100 is NX compatible (DEP), the rest are irrelevant.

Finally you've got `NumberOfRvaAndSizes`. This tells you how many entries there are in the directory table. The directory table tells the loader where certain optional structures are in memory. The directory table covers things like imports, exports, exception tables, digital signatures, relocations, debug info, thread-local storage config, IATs, and .NET metadata for CLR executables.

![image](https://user-images.githubusercontent.com/6430604/129746008-647e53df-65f7-47bf-9d06-6b79cfbcba37.png)

The data directories table is an array of up to 15 entries, each containing an RVA and size field. The `NumberOfRvaAndSizes` field is the number of valid entries in the table, plus one null entry on the end. So for a full table (the norm) it's 16, or 0x10. Normally you won't see any other value than 0x10 in a non-packed executable.

The meaning of each directory is hard-coded by its index, i.e. export = 0, import = 1, resource = 2, exception = 3, etc.

The RVA is the virtual address, relative to the image base, of the location of the data for that directory. These match up with sections, i.e. every directory points to some address in a section, rather than to an offset in the file.

The ones you care about at the Export Directory, Import Directory and the Import Address Table (IAT) Directory. I'll describe these later since it makes more sense to look at sections first.

Immediately after the data directories you have the sections table. 

![image](https://user-images.githubusercontent.com/6430604/129754540-4dbf57f8-453e-47b8-81a9-d7ebecbe2bc2.png)

Each entry in the table is called a [section header](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_section_header) and it has ten fields. A section lays out parts of program memory in virtual address space, telling the loader what page access flags to apply and what content to load.

The first field is the section name, which is an 8 byte string padded with nulls. These are effectively meaningless but the convention is to call the code section `.text`, the read-only data section `.rdata`, the read-write data section (for storing globals and setting their initial values) `.data`, any resources in `.rsrc`, and there are others for various other purposes. The names don't do anything, they're just for identification purposes.

Next are the Virtual Size and Virtual Address. These specify where the section should be mapped in memory, relative to the base address of the module, often referred to as an RVA. The virtual address must be aligned to `SectionAlignment`. The virtual size can be any number (unaligned), specifying exactly how many bytes from the file must be copied into the memory region. The allocated memory region itself will be rounded up to the nearest page boundary, so if you specify a size of 0x3E4C the section will be 0x4000 bytes in memory, but only the first 0x3E4C bytes will have data written into them.

After that you've got the Raw Size and Raw Address. These specify where the section's data is stored in the file. The raw address *and* raw size must be aligned to `FileAlignment`.

The other fields are unimportant, other than the Characteristics field which has flags about how the section works. The top nibble specifies the page protection flags: 0x2 for executable, 0x4 for readable, 0x8 for executable. There's also the "contains code" flag (0x20) and "contains initialised data" (0x40) flags at the bottom end of the field, which you shouldn't need to care about since they don't actually affect the functionality. The `.text` section usually has Characteristics value of 0x60000020, i.e. read+exec, contains code. The `.rdata` is readable, contains initialised data. The `.data` is read+write, contains initialised data.

You can translate between an RVA and a file offset using the table. Given an RVA, you scan through the section table, find the section that contains that RVA (i.e. RVA >= Virtual Address && RVA < Virtual Address + Virtual Size). You then subtract the RVA from the Virtual Address of the section to get the offset of that address in the section, and add it to the Raw Address to get the file offset.

Here's a code example in Python:

```python
def rva_to_offset(rva):
  for section in sections:
    if rva >= section.VirtualAddress and rva < (section.VirtualAddress + section.VirtualSize):
      sectionOffset = rva - section.VirtualAddress
      return section.RawAddress + sectionOffset
  return null
```

You can do the inverse, too, i.e. go from an offset to RVA:

```python
def offset_to_rva(offset):
  for section in sections:
    if offset >= section.RawAddress and offset < (section.RawAddress + section.RawSize):
      sectionOffset = offset - section.RawAddress
      return section.VirtualAddress + sectionOffset
  return null
```

You can also convert from a relative virtual address (RVA) to a virtual address (VA) by adding the PE's `ImageBase` field value to the RVA. So, for example, an RVA of 0x2000 would have a VA of 0x140002000, given the `ImageBase` of 0x140000000 shown in this particular PE. The VA is useful because it specifies the address that would be used in the real running program if the module was loaded at its preferred base address.

That's pretty much it for sections.

The export directory is the really important one for what you want to do here, i.e. make API calls from shellcode.

Normally on Windows your application imports the APIs for you so you don't have to worry about this. This is done via the import table and the IAT. The import table has entries for each DLL you want to import APIs from, then a set of imports for each of those DLLs. When the program starts, the Windows image loader loads the libraries into the program memory space, then finds the required imports and writes the addresses of the API functions into the import address table (IAT).

You can also dynamically load libraries with `LoadLibrary`, and then find APIs by name in a loaded library with `GetProcAddress`. But the thing is, you need to know where those APIs are in the first place to make those API calls to find other API addresses - a catch 22. However, if you can find those two APIs through some other method, you can use them to easily and reliably load any API you like. Both of those two APIs are in kernel32.dll, to make things a bit easier.

Instead of trying to find the APIs you want via the _import_ directory of the program executable, you can instead find them via the _export_ directory of the DLL that contains the exports you want. As long as you know where that module is in memory, you can find the export directory, and find the APIs!

The export directory is a little simpler than the import directory. It starts with a header:

![image](https://user-images.githubusercontent.com/6430604/129806342-c8b7e23d-3c60-4587-b15f-ccd5685b4fc0.png)

`Name` is the RVA of a null-terminated string that specifies the name of the DLL. If you convert the RVA to an offset you'll find the string in the file there. In this case I'm using kernel32.dll as an example:

![image](https://user-images.githubusercontent.com/6430604/129806549-2abc5c69-26be-4e1a-9776-aa304a8df6c9.png)

`NumberOfFunctions` is the number of exported functions, unsurprisingly.

`NumberOfNames` is the number of names in the export name table. This can be different to the number of exported functions, because some functions can be exported by ordinal (index in the table) rather than by name.

The export table is effectively three arrays. One for the RVAs to the functions (i.e. RVAs that point to the first instruction of the functions), one for the RVAs to the ordinals, and one for the RVAs to the function names. So for each entry you have a function, an ordinal, and a name.

`AddressOfFunctions` is the address of the function RVA list, which is basically an array of RVAs (kinda like pointers, here) to the function implementations.

`AddressOfNames` is the same but for RVAs to the name strings. Each is null-terminated.

`AddressOfNameOrdinals` is another array that specifies the ordinal of each function. Each is a 16-bit value.

![image](https://user-images.githubusercontent.com/6430604/129808491-3f717153-b7d7-4a5c-8ed3-2565ad0c6cb0.png)

So basically you've got:

```c
void* Functions[NumberOfFunctions];
char_t* Names[NumberOfNames];
uint16_t NameOrdinals[NumberOfNames];
```

Each function can be accessed by those indices. Functions with no name are importable by their ordinal (index into the array) - not to be confused with a name ordinal, which is different. Don't worry about ordinals too much, they don't come up very often and you don't really care about them here.

So to find a function by its name in the export table, you look at the `AddressOfNames` field to get the RVA of the names array, then use that to loop through each of the name RVAs to find the one that matches the name of the API you want. That gives you the index into the other arrays to find where the function is.

For example:

```c
void* getFunction(const char* functionName)
{
  for (int n = 0; n < exportDirectory->NumberOfNames; n++)
  {
    if (strncmp(functionName, exportDirectory->Names[n], peHeader->SizeOfImage) == 0)
    {
      return exportDirectory->Functions[n];
    }
  }
  return NULL;
}
```

Keep in mind that this gives you the RVA, so if you want the virtual address you need to add the base address of the module.

Remember that you can find the address of the module you want using the PEB. So let's say you want to find `LoadModule` and `GetProcAddress` from kernel32.dll at runtime - here's the steps in pseudocode:

```c
PEB* peb = read_gs_register();
PEB_LDR_DATA* ldr = peb->Ldr;
// start at the first node
LIST_ENTRY* currentNode = &ldr->InLoadOrderModuleList;
IMAGE_DOS_HEADER* kernel32_dos = NULL;
do
{
  // get LDR_DATA_TABLE_ENTRY after LIST_ENTRY
  LDR_DATA_TABLE_ENTRY* entry = (LDR_DATA_TABLE_ENTRY*)(
    ((uint8_t*)currentNode) + sizeof(LIST_ENTRY)
  );
  USHORT length = currentNode->BaseDllName->Length;
  wchar_t* dllNameStr = currentNode->BaseDllName->Buffer;
  // case-insensitive wide string comparison, with length limit
  if (wcsnicmp(L"kernel32.dll", dllNameStr, length) == 0)
  {
    // this is kernel32
    kernel32_dos = (IMAGE_DOS_HEADER*)currentNode->DllBase;
    break;
  }
  // not kernel32, try the next module
  currentNode = currentNode->Flink;
}
while (currentNode != NULL && currentNode != &ldr->InLoadOrderModuleList);

// did we find kernel32?
if (!kernel32_dos)
  return -1;

uint8_t* kernel32_base = (uint8_t*)kernel32_dos;

// find the NT header at the offset specified by e_lfanew
IMAGE_NT_HEADERS64* ntHeader = (IMAGE_NT_HEADERS64*)(
  kernel32_base + kernel32_dos->e_lfanew
);

// get the file & PE (optional) headers
IMAGE_FILE_HEADER* fileHeader = &ntHeader->FileHeader;
IMAGE_OPTIONAL_HEADER64* peHeader = &ntHeader->OptionalHeader;

// data directories are directly after the PE (optional) header.
IMAGE_DATA_DIRECTORY* directories = (IMAGE_DATA_DIRECTORY*)(
  kernel32_base + sizeof(IMAGE_OPTIONAL_HEADER64)
);

// find the sections
size_t sizeOfDirectories = sizeof(IMAGE_DATA_DIRECTORY) * peHeader->NumberOfRvaAndSizes;
IMAGE_SECTION_HEADER* sections = (IMAGE_SECTION_HEADER*)(
  kernel32_base + sizeof(IMAGE_OPTIONAL_HEADER64) + sizeOfDirectories
);

// get the virtual address of the export directory
IMAGE_EXPORT_DIRECTORY* exportDir = (IMAGE_EXPORT_DIRECTORY*)(kernel32_base + directories[0]->RVA);

// get the export arrays
DWORD* nameRVAs = (DWORD*)(kernel32_base + exportDir->AddressOfNames);
DWORD* functionRVAs = (DWORD*)(kernel32_base + exportDir->AddressOfFunctions);

void* fnLoadLibrary = NULL;
void* fnGetProcAddress = NULL;

for (int n = 0; n < exportDir->NumberOfNames; n++)
{
  char* name = (char*)(kernel32_base + nameRVAs[n]);
  void* func = (void*)(kernel32_base + functionRVAs[n]);
  if (strcmp("LoadLibrary", name) == 0)
    fnLoadLibrary = func;
  if (strcmp("GetProcAddress", name) == 0)
    fnGetProcAddress = func;

  if (fnLoadLibrary != NULL && fnGetProcAddress != NULL)
    break;
}

// did we find the APIs?
if (fnLoadLibrary == NULL || fnGetProcAddress == NULL)
  return -2;

// ok, now you've got the address of LoadLibrary and GetProcAddress and you can call them!
```

Once you've got `LoadLibrary` and `GetProcAddress` you can just get any API you like, or load any DLL:

```c
HANDLE hKernel32 = LoadLibrary("kernel32.dll");
SOME_FUNCTION_TYPE fnOpenProcess = GetProcAddress(hKernel32, "OpenProcess");
```

So that's pretty much it!

> The loader maps in all the necessary data, then jumps to the original entry point. For ELF/Linux the main problem is the vm.max_map_count limit. I am not sure if there are similar limits for PE/Windows. The HANDLE limit of 16M should not be a problem.

As far as I know there is no limit to the number of mapped sections, if you're doing the mapping dynamically, short of the number of pages you can have in virtual memory at least.

I know this was a long one but hopefully this gets you completely up to speed with PE headers. I recommend having a look through some of the guides online that explain the full format in more detail if you need reference. The MSDN docs are good too.

Let me know if anything was unclear! :)

**Comment by gsuberland** [comment]
I ended up turning the above into a blog post because I write far too much 😅

It's mostly what I said here but might be more easily readable as reference if you're working on stuff and want to look back through: https://codeinsecurity.wordpress.com/2021/08/18/a-primer-on-windows-pe-files-and-doing-api-calls-without-knowledge-of-memory-layout/

**Comment by GJDuck** [comment]
Thanks again for the detailed write up & I think you have answered most of my questions.  I now think a Windows/PE port is feasible and this is something that the project needs to do sooner or later, so I think I will start looking into implementing this.  I think however it would still be a lot of work so may take a while, especially since I need to split my time.

**Comment by gsuberland** [comment]
No problem at all. If you run into any problems or have questions, just let me know :)

**Comment by GJDuck** [comment]
I've built a prototype that injects code into existing PE executables by adding a new section.  Some things I (re?)discovered:

- Windows seems to want code/data to be contiguous, i.e.,  no gaps.  Linux/ELF does not care.
- There seems to be space to add a new section in all the PE files tested so far (`notepad.exe`, `tar.exe`, etc.), so this trick works at least.
- It also seems easy to extend the number of sections by moving data.  This is probably the correct way to load E9Patch trampolines, as opposed to `MapViewOfFile`.  Apparently modern Windows supports the full 65535 sections (not yet untested).
- Getting `GetProcAddress` from `kernel32.dll` seems to work fine, although I've only tested something simple (`WriteConsole`).
- For some reason my prototype generates broken binaries if ASLR is enabled in the PE file.  However, when I modify the binary to disable ASLR, it will run fine.  The exit status (when ASLR is enabled) is `STATUS_STACK_BUFFER_OVERRUN`.  This seems to stem from a `__fastfail` in `ntdll.dll` with error code `0xa`, at least according to `x64dbg`.  However, the error code `0xa` seems undocumented.
- If there is a problem with the binary, it is very difficult to debug.  Windows will usually just give a generic error message.

**Comment by gsuberland** [comment]
I believe the `STATUS_STACK_BUFFER_OVERRUN` behaviour on ASLR binaries may be related to an export address table access filtering (EAF) exploit mitigation. This mitigation works by marking the export address table of kernel32, kernelbase, and ntdll as a guard page. When you try to access the page, it raises an exception. The EAF handler then handles that exception and checks if the address attempting to access these pages is part of a legitimate module. I would have thought that your code would pass the EAF test, but perhaps it is checking if the section being executed has the "Contains Code" flag set - I am unsure.

One way to see if it is related to exploit mitigations is to open Event Viewer and check the Operational and WHC logs under Applications and Services Logs -> Microsoft -> Windows -> Windows Defender. For EAF, the event IDs you're looking for are 13 through 18. There's a handy reference for all the exploit guard event IDs [here](https://github.com/palantir/exploitguard).

If you can share your PoC for injection I can debug it and see if I can figure out what's going wrong.

**Comment by GJDuck** [comment]
Thank again for taking the time to write this up.  I think changing the `ImageBase` should be quite feasible, although it will not be a priority initially.

I think the final obstacle is how to handle TLS callbacks.  These are a problem since they are called before the entry point, meaning that the `.text` section may be executed before the trampolines have been put in place (resulting in a crash).  I think the solution will be to replace the first TLS callback with the injected loader code, rather than the entry point.

If that works, the roadmap to Windows PE support is as follows:
1. Add Windows PE executable support to E9Patch
2. Add Windows PE executable support to E9Tool
3. Port both E9Tool and E9Patch to Windows [optional]
4. Add Windows PE DLL support for E9Patch and E9Tool

Step 1. should be relatively easy now the design is settled.  Step 2. is somewhat harder, since E9Tool is currently very ELF specific.  Step 3. is similarly hard, since the E9Tool/E9Patch code base is Linux specific.  This step could be made optional if porting these tools is too much work (i.e., you can still rewrite Windows binaries, but only using Linux or WSL, similar to "cross compiling").  I think step 4. should be relatively easy, but will probably need `ImageBase` adjustment to be implemented first.

**Comment by GJDuck** [comment]
An experimental version of E9Patch for Windows is available here:

* [https://github.com/GJDuck/e9patch/tree/windows](https://github.com/GJDuck/e9patch/tree/windows)

To try it out (e.g., on `calc.exe`), do the following (on Linux):

    (copy calc.exe from Windows)
    $ ./build.sh
    $ ./e9tool -M true -A passthru ./calc.exe -o calc1.exe

Then (on Windows):

    (copy calc1.exe from Linux to c:\)
    > c:\calc1.exe

It should print some debug information but otherwise run normally.

The current version is for testing only, and is a long way from a usable tool.  Some caveats:
- E9Tool is hacked to only accepted Windows PE.  (the hacked E9Tool is a placeholder for step 2. of the roadmap)
- Only trivial actions like "passthru" will work. (no syscalls yet!)
- Windows EXEs only, no DLLs.
- Will likely crash if the EXE uses TLS callbacks.
- Might crash if the ImageBase is in "polluted" address space.

**Comment by gsuberland** [comment]
> I think the final obstacle is how to handle TLS callbacks. These are a problem since they are called before the entry point, meaning that the `.text` section may be executed before the trampolines have been put in place (resulting in a crash). I think the solution will be to replace the first TLS callback with the injected loader code, rather than the entry point.

The TLS callbacks are executed by the loader in the same order as they are listed in the PE structure, and execute synchronously.

When the process starts, each callback is executed synchronously, in order, in the context of the main thread of the process. The `dwReason` parameter to the TLS callback is `DLL_PROCESS_ATTACH`. This occurs before the main entry point executes, as you know.

When a thread is created, each callback is executed synchronously, in order, in the context of the new thread. The `dwReason` parameter to the TLS callback is `DLL_THREAD_ATTACH`. This occurs before the entry point of the thread executes. One exception is that `DLL_THREAD_ATTACH` is not raised for the main thread, since `DLL_PROCESS_ATTACH` is literally just a special-case `DLL_THREAD_ATTACH` event for the main thread anyway.

When a thread exits normally (i.e. the thread procedure exits), each callback is executed synchronously, in order, in the context of the exiting thread. The `dwReason` parameter to the TLS callback is `DLL_THREAD_DETACH`. This occurs after the thread procedure returns, but before the thread is actually disposed of. A key detail, though, is that terminating a thread (i.e. with `TerminateThread`) causes the thread to be immediately terminated, skipping the TLS callback.

All of these operations block the thread that the callback relates to, but no other threads, so TLS callbacks can still execute in parallel with code executing in other threads (including other TLS callbacks). As such, you need to be careful about cross-thread accesses. The only exception is `DLL_PROCESS_ATTACH`, which is guaranteed to be called when the process only has one running thread, so you don't need to worry about parallel execution.

I think a good approach here is to actually have the entire patcher's setup stub (the code you'd usually have run first by patching the entry point) run from a TLS callback if the executable already has one. Your injected TLS callback would look something like this:

```cpp
// spinwait lock for patching completion
volatile unsigned long _e9patch_complete = 0;

// statically write the address of the original TLS entry here, so the code knows where to call
volatile PIMAGE_TLS_CALLBACK _e9patch_original_tls = NULL;

void e9patch_tls_callback(PVOID hModule, DWORD dwReason, PVOID pContext)
{
    // first check if the e9patch stub has already completed (i.e. _e9patch_complete is nonzero)
    // note: InterlockedCompareExchange is an intrinsic, not a Windows API, so it doesn't need resolving.
    if (InterlockedCompareExchange(&_e9patch_complete, 0, 0))
    {
        // e9patch init already completed, so just pass this back to the original callback
        _e9patch_original_tls(hModule, dwReason, pContext);
        return;
    }

    if (dwReason == DLL_PROCESS_ATTACH)
    {
        // set up e9patch, passing a flag to say "don't automatically jump to OEP"
        e9patch_init(E9PATCH_FROM_TLS_CALLBACK);
        // set the complete flag
        InterlockedIncrement(&_e9patch_complete);
    }
    else
    {
        // DLL_THREAD_ATTACH or DLL_THREAD_DETACH was somehow hit before the patcher finished
        // this shouldn't be possible, so raise an assertion failure (or something like that)
        assert(false);
        // if it turns out there is some legit reason that this might happen, here's a graceful way to deal with it:
        // spinwait for _e9patch_complete before dispatching the original handler.
        while (!InterlockedCompareExchange(&_e9patch_complete, 0, 0)) { }
        _e9patch_original_tls(hModule, dwReason, pContext);
    }
}
```

This should guarantee that your loader stub executes before anything else, without running into other TLS callbacks, and without breaking the callback you're replacing.

The case where `DLL_THREAD_ATTACH` is hit before the `DLL_PROCESS_ATTACH` event completes _might_ happen if an external process calls `CreateRemoteThread` on your process before `e9patch_init` completes. I'm not sure if this is possible - it might stall the `CreateRemoteThread` call until the TLS callback on the main thread completes - but you can at least handle this with a spinwait as shown.

**Comment by gsuberland** [comment]
Random aside, for debugging: if you want to get the current process ID and thread ID at runtime, before you resolve APIs, you can read them from the TEB.

On x64, offset 0x40 has a `CLIENT_ID` struct, which contains a pair of `HANDLE` type values (which is just typedef `void*`) for the process ID and thread ID. You can read them with `__readgsqword` in VC++, e.g.:

```cpp
uint64_t pid = __readgsqword(0x40);
uint64_t tid = __readgsqword(0x48);
```

The Microsoft C++ compiler will usually inline `GetCurrentProcessId()` and `GetCurrentThreadId()` to just read the TEB like this anyway, but this saves you having to worry about resolving exports.

**Comment by GJDuck** [comment]
Just a quick update: The current E9Tool/E9Patch tools are stable enough to successfully rewrite programs such as `cmd.exe`.  The E9Tool `passthru`, `print` and `call` actions have been ported to Windows:

- https://github.com/GJDuck/e9patch/tree/windows

The overall design appears to be validated.  The patched binaries can do 1000s of mappings during program initialization with a reasonable delay, and the patched binaries run as expected.

The patched binaries will occasionally trigger a false positive from Windows Defender.  This is probably not very surprising.  It can be fixed by whitelisting the binary.

Some remaining TODOs:
- Merging into the main branch (hopefully soon).
- Rewriting Windows PE DLLs.  Rebasing has been implemented, which should help.
- Porting `stdlib.c` to Windows (requires a bit of work).  Although `call` actions have been implemented, there is currently no useful programming environment, which makes building applications difficult.  This can be added later.

**Comment by GJDuck** [comment]
I've merged the initial cut of Windows PE support, so this issue can be closed.  If there are any specific problems, then these can be put in seperate issues.

The support is still experimental and undocumented, but hopefully this will improve over time.

Many thanks to @gsuberland for providing the initial impetus and technical information.  This was really helpful.

**Comment by gsuberland** [comment]
Thanks for putting the work in and getting this implemented!
