### ISSUE TITLE
Capstone version needs to be configured for patching Chrome

### ISSUE THREAD

**Issue by yuntongzhang** [GJDuck/e9patch#11]
This is an issue with the capstone disassembler rather than e9patch itself.

For the more general use cases, capstone version [4.0.2](https://github.com/aquynh/capstone/tree/4.0.2) should be used for reliable disassembly. Using older versions has caused disassembly issues when patching some SPEC2006 benchmarks (omnetpp, xalancbmk, dealII) under certain cases.

However, version [4.0.2](https://github.com/aquynh/capstone/tree/4.0.2) cannot handle some AVX512 instructions for some reason, and these instructions are present in the Chrome executable. Therefore, when patching Chrome, it is recommended to use an older version such as [e3f1067](https://github.com/aquynh/capstone/commit/e3f106739a6ae78d47772dff31062d644ea21078).

The capstone version is configurable with the e9patch build script.

**Comment by GJDuck** [comment]
Thanks for documenting this issue.  It seems each version of Capstone we have tried has some limitation or another.

Since E9Patch is `x86_64` specific, perhaps the long term solution is to switch to using [XED](https://github.com/intelxed/xed) instead.  Since XED is created by Intel, it should be accurate.

Another issue with Capstone is that the disassembled instruction representation is relatively large.  This can equate to >70GB of data for large applications such as Chrome.  (This is only a problem for applications that need to analyze the entire disassembly.  By default, E9Tool/E9Patch uses incremental disassembly so it is not normally a problem).  Perhaps XED uses a more compact representation.

**Comment by tathanhdinh** [comment]
There was some work on comparing the disassembly accuracy of existing libraries, e.g. the [reseach](https://blog.trailofbits.com/2019/10/31/destroying-x86_64-instruction-decoders-with-differential-fuzzing/) of Trail of Bits fuzzed different disassembly libraries (Capstone, Xed, Zydis, libopcodes, udis86), and it came to a conclusion:

> Not everything is doom and gloom. If you need accurate instruction decoding (and you do!), you should use XED or Zydis. libopcodes is frequently close to Zydis and XED in terms of instruction support but consistently records false positives and decodes just prefixes as valid instructions. Capstone reports both false positives and false negatives with some regularity. udis86 (not shown above) behaves similarly to libopcodes and, given its spotty maintenance, should not be used.

I've used both Xed and Zydis, for me Zydis has a very nice API, it's also lightweight and fast (even faster than Xed). Besides, Xed comes also with instruction encoding, which may be not needed by e9patch.

**Comment by GJDuck** [comment]
Thanks @tathanhdinh, I think Zydis looks like a promisng alternative.  Instruction encoding could be useful one day, e.g., it might be nice to have a feature where the user can specify custom trampolines in assembly (rather than effectively machine code, as is currently the case).  But this would be a lot of work to design and implement.

The current E9Tool is somewhat intergrated with Capstone, so it'd take some effort to move to a new disassembler.  So this is more of a medium or long-term goal anyway.

**Comment by GJDuck** [comment]
I've replaced Capstone with Zydis which will hopefully fix this issue.  I've tested the new version on Chrome but not yet SPEC.

The code has been refactored so that replacing the disassembler (e.g., back to Capstone or XED) should be a lot easier now.  In theory, it should also be possible to support multiple disassemblers if we want.

The plugin interface also had to be changed to remove the Capstone dependency.  The new interface should be better, but existing plugins will need to be updated.
