### ISSUE TITLE
 e9loader error: failed to find shared object path (errno=2

### ISSUE THREAD

**Issue by hardik05** [GJDuck/e9patch#19]
Repro:
1. download program from here:
```
wget https://github.com/hardik05/Damn_Vulnerable_C_Program/blob/master/imgRead.c
```
2. compile using gcc:
```
gcc imgRead.c -o imgRead_gcc
```
3. instrument with e9afl
```
./e9afl imgRead_gcc it will generate imgRead_gcc.afl
```
4. run  imgRead_gcc.afl this will give error:
```
 ./imgRead_gcc.afl
e9loader error: failed to find shared object path (errno=2)
[1]    2661 abort (core dumped)  ./imgRead_gcc.afl
```

**Comment by GJDuck** [comment]
Unfortunately there is no quick workaround.  You could try running Linux in something like VirtualBox.

I've transferred the issue to the E9Patch repository, since this is really an E9Patch limitation.  The loader uses `/proc/self/map_files/` to find its own image, so additional data can be mmap'ed in.  A simpler method would be to use `/proc/self/exe` which WSL probably does support, however this method does not work for shared libraries.

There may be other WSL incompatibilities even if this issue is fixed.

**Comment by hardik05** [comment]
Oh okay. Thanks, I will use vm then..

**Comment by GJDuck** [comment]
The `/proc/self/map_files/` issues should be fixed for ELF executables at least.  However, the rewritten executables still do not seem to work correctly user WSL for different reasons, such as a crash or `ENOMEM` error during initialization.

**Comment by GJDuck** [comment]
I think this issue was resolved, so I will close it.
