### ISSUE TITLE
error: failed to disassemble the ".text" section of openssl

### ISSUE THREAD

**Issue by mirzamomen** [GJDuck/e9patch#20]
Steps to reproduce:

1- Download and compile openssl

`git clone https://github.com/openssl/openssl.git`
`cd openssl`
`git checkout c74188e`
`./config  no-shared`
`make build_generated`
`make apps/openssl`

2- Run the following command:

`./e9tool -M 'asm=cmp.*' -A 'call entry(addr,instr,size,asm)@print'  [PATH]/apps/openssl`

I get this error: 

`failed to disassemble the ".text" section of "apps/openssl"; this may be caused by (1) data in the ".text" section, or (2) a bug in the third party disassembler`

**Comment by mirzamomen** [comment]
My OS is:

Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by GJDuck** [comment]
Thanks for the report.  This is a limitation of E9Tool, and the problem is specified in the error message:

    (1) data in the ".text" section

Some versions of `openssl` put data in the `.text` which causes the basic linear disassembler or E9Tool to fail.  It is possible to manually correct this problem by "excluding" the regions which contain data, e.g.:

    ./e9tool -E addr1..addr2 ...

where `addr1..addr2` is the range of the data embedded in the code.  Multiple `-E` options may be required for multiple data.

Currently, E9Tool only supports a basic linear disassembler, similar to `objdump`.  One day it would be nice to support some other kinds of disassemblers, such as recursive, which may be able to automatically avoid this problem for common cases (although the static disassembly problem is not perfectly solvable in the general case).  This is on the todo list.
