### ISSUE TITLE
error building e9patch

### ISSUE THREAD

**Issue by hollerith** [GJDuck/e9patch#21]
Hi, 

I encountered a problem with running the build scripts in my env for e9afl and e9patch. 

```Linux triton 5.10.0-6parrot1-amd64 #1 SMP Debian 5.10.28-6parrot1 (2021-04-12) x86_64 GNU/Linux```

https://pastebin.com/ErsKNENR

Here's some asciinema of the errors. It fails to build e9patch because of the double float.  

``` error: SSE register return with SSE disabled```

**Comment by GJDuck** [comment]
The problem appears to be `std::abs(long double)` defined in a header file but never used.  Since the function is never used, the compiler should not generate an error, but it seems that it does so anyway.

I will need to look into this.  As a temporary fix, you can try removing `-mno-sse` from the `Makefile`.  Alternatively, you can try the E9AFL binary releases if you do not plan to modify the source code: https://github.com/GJDuck/e9afl/releases

**Comment by farimani** [comment]
You can build it on debian 9 (stretch). otherwise both buster and bullseye, as well as ubuntu 20.04 produce the above error.
