### ISSUE TITLE
Question about the output binary

### ISSUE THREAD

**Issue by qunqunqun** [GJDuck/e9patch#28]
I have a simple C code
```#include <stdio.h>
int myadd(int a, int b) {
    return a + b;
}

int mysub(int a, int b) {
    return a - b;
}

int myp() {
    return 1;
}

int main() {
	int a = 1;
	int b = 2;
	printf("%d,%d,%d,%d\n",a + b, myadd(a,b) ,mysub(a,b), myp());
	return 0;
}
````
and use ' ./../e9tool -M 'asm=sub.*' -A print a' to generate binary 'a.out'
using 'readelf -h a.out' and the output is 
```ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x20e9e9090
  Start of program headers:          64 (bytes into file)
  Start of section headers:          8952 (bytes into file)
```  
I'm confused with the Entry point address.
And I use objdump to check the instruction, however the two binaries seems the same. But a.out truly prints the 'xor'.
How does e9patch manage addresses of the new elf ?

**Comment by GJDuck** [comment]
E9Patch changes the entry point to injected code (at address `0x20e9e9090`) that (1) loads the trampolines, and (2) replaces `.text` with the patched version.  The latter explains why `objdump` shows the original code and not the patched version.  The patched code will be visible dynamically, e.g., when using `gdb` to disassemble the program while it is running.

You can also patch the code statically: simply pass the `-s` option to E9Tool.  Now the patched code will be visible via `objdump`.

Statically patched code is not the default since it causes problems with some binaries that use advanced dynamic linker features.  For such binaries, the dynamic linker will invoke functions in the binary before the trampolines have been set up, leading to a crash.  Only some binaries are affected, and if a given binary works with `-s`, then it is recommended since it leads to a smaller patched binary size.

**Comment by qunqunqun** [comment]
Thank you for answering my simple questions. However I has some questions.
1. "advanced dynamic linker features" -- could u provide some learning materials or site about  linker features? I am a Rookie interested in binary rewriting
2. From my perception, from binary to binary is  "Statically patched". So I'm still confused about" (2) replaces .text with the patched version."
For example, I use "gdb a.out"
```
Reading symbols from a.out...done.
(gdb) b main
Breakpoint 1 at 0x686: file a.c, line 16.
(gdb) r
Starting program: /home/qun/Desktop/Disassembly/e9patch/mytest/a.out 
xor ebp, ebp
xor ebx, ebx
3,3,-1,1
[Inferior 1 (process 23823) exited normally]
(gdb) 
```
break at main but no break points while running.
I will do some more experiments and try to understand it.

Finally, Thanks again for your patience.

**Comment by GJDuck** [comment]
1.  One example is if the program exports its own `malloc`.  In this case, the dynamic linker will use the program's exported `malloc` rather than its own version.  But this means the program's `malloc` will be called before trampolines have been set up, causing a crash.  I think there are other ways the dynamic linker will call functions exported by the program, but do not know them off the top of my head.
2. E9Patch injects a loader that initializes the trampolines.  With static patching disabled, the original `.text` section will preserved in the file, and the loader will literally overwrite the `.text` section at runtime with the patched version.  This solves issues caused by (1), but does mean the initial calls from the dynamic linker are uninstrumented.

As for the problem with `gdb`, this is a side effect of (2).  Basically, `gdb` sets a breakpoint in the code (by replacing the instruction at the breakpoint with `int3`), but the breakpoint is clobbered when the patched `.text` is loaded by the E9Patch loader.  This is a known issue.

One workaround is to use E9Patch to insert trap instructions, with the `--trap` options or E9Tool `trap` instrumentation.  This has the same effect as a breakpoint in `gdb`, but will not be clobbered by the loader.

**Comment by GJDuck** [comment]
Unfortunately there is no easy-to-understand guide for the internals of E9Tool/E9Patch.  Probably the only option is to read the PLDI paper, but even that is missing some information like the recent optimizations.

**Comment by qunqunqun** [comment]
Hello, I have some small questions. I wanna try to learn about how e9patch modify the memory and output the new binary.
What I wanna to do now is patch instructions with 5 bytes. 
First, when calculate the address " b2c:	e8 1f fb ff ff" the debug information are like.
```
lo address: 80000b32, hi address: 7ffff650
lb:203000,ub:203016
```
I know the above address is the available virtual address, I don't know how to get the virtual addr, and how to calculate the real address(file offset in my opinion).
Second, the new instruction is "b2c: e9 cf 24 20 00  jmpq   203000 <_end+0xfe8>". since the origin code is saved which means offset are same as origin. Which section does the new trampolines belong to? How e9patch add new code and make sure it can be load to right address? I have search but get little useful information. 
Hope for your help~

**Comment by qunqunqun** [comment]
And I use gdb to find 
``` 
» gdb -q -nh a.out                                                                      1 ↵
Reading symbols from a.out...(no debugging symbols found)...done.
(gdb) info file
Symbols from "/home/qun/Desktop/Disassembly/e9patch/mytest/a.out".
Local exec file:
	`/home/qun/Desktop/Disassembly/e9patch/mytest/a.out', file type elf64-x86-64.
warning: Cannot find section for the entry point of /home/qun/Desktop/Disassembly/e9patch/mytest/a.out.
	Entry point: 0x20e9e9078
```
How to calculate the entry point ? There origin is "0x6f0"

**Comment by GJDuck** [comment]
The entry point code is here: https://github.com/GJDuck/e9patch/blob/master/src/e9patch/e9loader_elf.cpp

The trampolines are not stored in any ELF segment/section, since the ELF format does not support adding new segments/sections easily.  Instead, there is a single E9Patch loader that is called when the program first starts.  The loader then loads the trampolines (from directly from data appended to the binary file) into their correct locations using `mmap()`, as well as other tasks such as calling the `init()` functions.  Once this is complete, the loader jumps to the "real" entry point and executions resumes as normal.

**Comment by qunqunqun** [comment]
What I wanna to do now is patch instructions with 5 bytes and there are some questions.
1. When patch the bytes over 5 bytes,would the virtual address of these trampolines be continuous? what I need is a continuous virtual memory address for my next work. By the way, since “ loads the trampolines into their correct locations using mmap()”, is that means I can get trampolines's virtual addresses without run it?
2. Since I patch useless instruction (use gcc  --function-instrumentation), I don't need the patched instruction occur in the trampolines, how could I modify code to achieve that.

Hoping for your answer!

**Comment by GJDuck** [comment]
> 1. When patch the bytes over 5 bytes,would the virtual address of these trampolines be continuous?

Yes, the trampolines will be packed contiguously where possible, such as when patching >= 5 byte instructions.

> I can get trampolines's virtual addresses without run it?

It is not currently supported.  It could be parsed from debug messages, e.g., by passing `--option --debug` to E9Tool.

> 2. I don't need the patched instruction occur in the trampolines, how could I modify code to achieve that.

Just add the `replace` keyword in front of your patch, such as:

        ./e9tool -M ... -P 'replace f()@example' ...

Here "`replace`" means the matching instruction is "replaced" by the patch (in this example, a function call).

**Comment by qunqunqun** [comment]
Thanks for the patience!
"Here "replace" means the matching instruction is "replaced" by the patch (in this example, a function call)." does this means the basic action like "empty" has those choice, I modify the variable replace default "true" and use " ./../e9tool -s -O0 -M 'asm=call.*' -A passthru --syntax=intel a" and the output could run correctly.
I will check the code and thanks again.

**Comment by GJDuck** [comment]
> does this means the basic action like "empty" has those choice?

Yes, ever since the patching language was redesigned, any kind of patch can be `before`/`replace`/`after`.  Previously it was limited to calls only.

> ./../e9tool -s -O0 -M 'asm=call.*' -A passthru

This is the old syntax, the new syntax will be: `./../e9tool -s -O0 -M 'asm=call.*' -P empty`

Something like `-P 'replace empty'` will effectively delete the instruction (i.e., "replace" the instruction with "empty").

**Comment by qunqunqun** [comment]
> It is not currently supported. It could be parsed from debug messages, e.g., by passing --option --debug to E9Tool.

I use "./../../e9tool -s -O0 -M 'asm=xor.*' -P 'replace empty' --debug --syntax=intel a" to patch the binary, however the info may not show the virtual address the trampolines will be.
```
debug: --------------------------------------
debug: 0xacd: patch call 0x6b0 [$empty] #0
debug: 0xa42: patch call 0x6d0 [$empty] #0
debug: 0xa07: patch call 0x6b0 [$empty] #0
debug: 0x9e4: patch call 0x6d0 [$empty] #0
debug: 0x9c2: patch call 0x6b0 [$empty] #0
debug: 0x9af: patch call 0x6d0 [$empty] #0
debug: 0x981: patch call 0x6b0 [$empty] #0
debug: 0x92c: patch call 0x6d0 [$empty] #0
debug: 0x8f2: patch call 0x6b0 [$empty] #0
debug: 0x89b: patch call 0x6d0 [$empty] #0
debug: 0x86f: patch call 0x6b0 [$empty] #0
debug: 0x819: patch call 0x6d0 [$empty] #0
............
+
[00000000000000030000000000000000]
-----------------------------------------------
input_binary          = /home/qun/Desktop/Disassembly/e9patch/mytest/test_a/a
input_mode            = Linux ELF executable
num_patched           = 12 / 12 (100.00%)
num_patched_B1        = 12 / 12 (100.00%)
```
1. Is the virtual address is fixed? I print out tactic_B1 
```
  const Alloc *A = allocateJump(B, I, T);
    printf("lb:%x,ub:%x\n",A->lb,A->ub);
    if (A == nullptr)
        return nullptr;
    Patch *P = new Patch(I, tactic, A);
```
The result is file offset like" lb:1000,ub:1005"

**Comment by GJDuck** [comment]
You need to pass `--option --debug` to E9Tool, not just `--debug`.  The `--option` flag passes the option down to E9Patch.

Yes, you can also just modify E9Patch to print the trampoline address.  The address will be fixed once the patch is committed (see the `commit()` function).

**Comment by qunqunqun** [comment]
Hi, I am trying to get virtual address of trampolines whiling running. However Address space layout randomization (ASLR) bothers me because the base address is random. I use perf to find
```          
a.out 10887 [011] 1996451.300991825:      55bd0ae80a15 main+0x0          pushq  %rbp
a.out 10887 [011] 1996451.300991825:      55bd0ae80a16 main+0x1        mov %rsp, %rbp
```
```
 a.out  9470 [004] 1996107.825827978:      563082079a15 main+      pushq  %rbp
 a.out  9470 [004] 1996107.825827978:      563082079a16 main+mov %rsp, %rbp
```
you can see the vaddr is not the same.

> The entry point code is here: https://github.com/GJDuck/e9patch/blob/master/src/e9patch/e9loader_elf.cpp

I wonder if I can modify the entry and do something else for example get the pid and virtual address of this proc ?

**Comment by GJDuck** [comment]
The base address is already stored in the `elf_base` variable.  The runtime address = ELF file address + `elf_base`.

The base address can also be passed to functions using the `base` argument.  Also see the `static` prefix for some arguments.
