### ISSUE TITLE
Regarding the offset for the registers

### ISSUE THREAD

**Issue by jjang3** [GJDuck/e9patch#38]
Good evening!

This question is regarding the `examples/state.c` example. 

**Summary of the question:** Is it possible to obtain the value of registers _before_ some arbitrary offset value (which I am not sure what it is) is added?

---

### Detail information to help understand the question:

I will use this example assembly code for my explanation:
```
0000000000001149 <foo>: 
    1149:       f3 0f 1e fa             endbr64  
    ...

0000000000001160 <main>: 
    116d:       e8 d7 ff ff ff          callq  1149 <foo> 
    1172:       48 8d 3d 8f 0e 00 00    lea    0xe8f(%rip),%rdi 
```

**Motivation**: Implementing a shadow stack based on function prologue/epilogue requires the value stored in `rsp` (which contains the return address of the `caller`) at the prologue so that we could push this value into the shadow stack (which will be checked upon `ret` instruction). 

Using the above assembly code, I tried to instrument the entry point of the function `foo` (which is `addr=0x1149`) and attempted to read the register by using the `state` argument (e.g., `state->rsp`).

This is the result I get from doing so (the `rsp` value is: `0x7ffeed8d2878`, and there are other pieces of information which I printed as I was trying to solve this issue by myself):
![image](https://user-images.githubusercontent.com/42549923/144694402-611d895b-0edb-448d-9da5-a6be1c05ecd1.png)

I tried to verify this `rsp` value by dynamically disassembling the original binary, and from the looks of it, **it seems correct, but with some caveats**

Below is the gdb result from the original binary breakpoint at the address `0x1149`:
![image](https://user-images.githubusercontent.com/42549923/144694491-7eb057a7-32cb-45c6-b699-ba6c2f00296a.png)

So the value of the `rsp` register at the address `0x1149` from the original binary is `0x7fffffffe0c8`.

From subtracting with the formula of `original - e9patched`, the offset result is `0x11272B850`. Would it be possible to obtain this offset value so that I could use it in the instrumentation?

The usage case of obtaining the `rsp` register value same as the original binary would be for something like this (which works in actual binary)
`__builtin_extract_return_addr(0x7fffffffe0c8); // 0x555555555172`

---

Thank you for any suggestions (and maybe this is not even possible, which is perfectly understandable) 
Kind regards,

**Comment by GJDuck** [comment]
> From subtracting with the formula of original - e9patched, the offset result is 0x11272B850. Would it be possible to obtain this offset value so that I could use it in the instrumentation?

The `rsp` values in the original and patched binaries should be exactly the same modulo [Address Space Layout Randomization (ASLR)](https://en.wikipedia.org/wiki/Address_space_layout_randomization).

In fact, isn't ASLR is the issue here?  The stack values come from different runs (one in gdb) which means the `rsp` values differ by some random offset.

**Comment by jjang3** [comment]
Thank you very much for your reply,

The random offset was indeed due to ASLR (I apologize that I didn't think of this ahead of time). Therefore, I disabled the ASLR and attempted to do the same thing, and as expected, the RSP register value looks saner.

However, I feel that the register value is still off by a little bit?

<img width="865" alt="Screen Shot 2021-12-04 at 2 59 35 PM" src="https://user-images.githubusercontent.com/42549923/144723003-9dd1d5c8-4e56-40fd-9528-d5bce9f3d069.png">
<img width="395" alt="Screen Shot 2021-12-04 at 2 56 57 PM" src="https://user-images.githubusercontent.com/42549923/144722955-97f3dc53-bab4-4f42-b237-b21826fe9275.png">

It seems like the register value is off by `0x50`, unless I missed something again.
Original: `0x7fffffffe148`
E9Patch: `0x7fffffffe198`

I will close the issue because the offset value matter is resolved thanks to your comment, but I still wanted to bring this to your attention!

Once again, thank you,
Sincerely,

**Comment by GJDuck** [comment]
> It seems like the register value is off by 0x50, unless I missed something again.

I had a look.  For some programs like `ls`, the `rsp` value appears to be different in the patched version, e.g.: `0x7fffffffdc50` (original) versus `0x7fffffffdc30` (patched).

However, it turns out that this was just a side effect of running the patched binary from a different directory.  When I copied the original `ls` to the same directy, then the `rsp` values will match (both `0x7fffffffdc30`).

So I think this is just an example of a general problem: to get the exactly same behaviour it might be necessary to exactly replicate the environment, depending on the program.

(This is more of a problem in Windows, where many programs moved out of `c:\Windows\system32` will stop working.  This can be confused a rewriting failure, whereas the rewritten binary is faithfully executing the original (broken) behaviour.)
