### ISSUE TITLE
In my patch code, can I call into a shared library?

### ISSUE THREAD

**Issue by MJChku** [GJDuck/e9patch#40]
Can I call into a shared library inside the function that I intend to insert ?
For example I want -P "entry()@binary" in entry(), I want to call a function defined in something.so.

**Comment by GJDuck** [comment]
> Can I call into a shared library inside the function that I intend to insert ?

Yes it is possible but requires a few steps:

1. Include `stdlib.c` with `LIBDL` defined:

        #define LIBDL
        #include "stdlib.c"

2. Pass a pointer to the dynamic segment to the `dlinit()` function inside `init()`:

        void init(int argc, char **argv, char **envp, const void *dynamic)
        {
            dlinit(dynamic);
            ...
        }

3. Use the usual `dlopen()` and `dlsym()` functions (see man pages), e.g.:

        handle = dlopen("libc.so.6", RTLD_LAZY);
        printf_func = dlsym(handle, "printf");

4. Call the function using `dlcall()`:

       dlcall(printf_func, "x = %d\n", x);

Note that function pointers returned by dlsym() cannot be called directly, and you must be `dlcall()`.  This is because the E9Tool instrumentation and the library code use an incompatible ABI, meaning that a direct call will likely crash.

More info:

* See the _Call Trampoline Dynamic Loading_ section in the [E9Tool user guide](https://github.com/GJDuck/e9patch/blob/master/doc/e9tool-user-guide.md).
* [Test case](https://github.com/GJDuck/e9patch/blob/master/test/regtest/dl.c) using dynamic loading.

**Comment by MJChku** [comment]
Thanks!!! I am glad I asked, was going to default a no to my question.

**Comment by MJChku** [comment]
Does dlcall support function with return value ? Doesn't seem to work.

**Comment by GJDuck** [comment]
It should work for integer or pointer return values, but not floating point.  Do you have a test case?

**Comment by MJChku** [comment]
I give up on this route, instead just generate a trap, and install a trap handler for what I want to do (which is way more heavier)


However, I do encounter one more issue. I want to patch a `trap` before a `CALL`, inside trap handler, I see `PUSH addr`, by decoding info passed to handler. the addr is near my call. I understand e9patch modified the call instruction bytes to insert trap, but is there a way to insert a trap, and in trap, I will see it's "CALL" that being trapped ?  

***
>For example I want:
`-M 'addr=0x4009a7'-P 'before trap' my_binary` 
I see 'push 0x4009ac' in trap, and I expect to see `call something`.

**Comment by GJDuck** [comment]
The trampoline cannot directly use the `callq` instruction, since it would push a trampoline address as a return address onto the stack, which potentially breaks transparency.  Thus (`callq target`) is translated into a (`push real-ret-addr`) instruction followed by (`jump target`), thereby pushing the "correct" return address onto the stack.

**Comment by MJChku** [comment]
Great thanks! Then callq == push in my case.
