### ISSUE TITLE
Any idea why binaries precompiled with -no-pie would be any less likely to need a super high memory limit upon execveing?

### ISSUE THREAD

**Issue by passthecilantro** [GJDuck/e9patch#41]
Hi, I just have a question (I think it is most related to e9patch) and I would like to learn more about your tools. Thank you in advance for developing these tools! 
I'm using e9patch/e9tool/e9afl to insert only my custom initialization function using E9Tool Plugin API specifically
 e9_plugin_init_v1() to run at program startup. 
When AFL and also afl-showmap tries to execute e9afl rewritten gcc (default -pie) binaries (with the default 
memlimit -m = 50, 50MB), The output of AFL reports OOM and that the forkserver crashed. The strace for AFL and
afl-showmap show that their execve returns ENOMEM and a SIGSEGV immediately occurs. The cause of the SIGSEGV,
according to the manpage for execve, is because there is most likely a resource exhaustion. 

On the e9afl readme it says a crashes might be due to insufficient memory limit and that I should increase the memory
limit, however even when I use a memory limit of -m 9000 with AFL and afl-showmap, I still get the same output with
 AFL and SIGSEGV for both AFL and afl-showmap. 

I've tried a few things to see if I could get this to work. I reduced mappings by passing compression=0 to the
e9tool in e9afl.cpp. I also made sure to use glibc malloc (using dlcall) instead of the implementation in stdlib.c
in 9patch which uses I believe 1GB. For additional context, my initialization function only dynamically allocates at
most 268MB. But even with these changes using -m 9000 still produces the same output and still appears to be an
insufficient memory limit. I would like to use a memory limit of -m=9000(9GB) because I want to run three parallel
fuzzing jobs and my machine only has 32GB RAM.

Finally (sorry for the long read), I noticed that if the binaries were precompiled with -no-pie then the -m 9000
memory limit is sufficient! If I use anything a lot less than -m=9000, I still get these failures even with -no-pie
precompiled binaries but that's okay. Sorry in advance of the naivety of my question. My question
is do you happen to have an idea why binaries precompiled with -no-pie would be any less likely to need a super
high memory limit upon execveing?

When looking at gdb and at /proc/pid/stat and other similar 
memory usage files for when AFL and afl-showmap executes e9afl binaries, I didn't happen to see e9afl rewritten no-pie
binaries use anywhere near even 9GB. Thank you again in advance!

**Comment by GJDuck** [comment]
The `-m` option for AFL is well-known to be problematic.  The issue is that `-m` limits the *virtual* memory size of the program, and not the *physical* memory limit (RSS size).  For many programs, the virtual and physical memory will roughly correspond, meaning that the virtual memory limit can be a good proxy for limiting physical memory.

However, this does not apply for E9Patch'ed programs, where the virtual memory usage can be significantly larger than the physical memory usage.  See the "*physical page grouping*" optimization from the PLDI paper.

More information about the `-m` problem is documented [here](https://afl-1.readthedocs.io/en/latest/notes_for_asan.html).  This is for AddressSanitizer but the problem is the same.

To fix the problem, the recommendation is to tune `-m LIMIT` to the smallest value that does not result in spurious crashes.  Or you can try `-m none` to remove the limit altogether (at the risk of a haywire program consuming all of the system memory).

> I would like to use a memory limit of -m=9000(9GB) because I want to run three parallel fuzzing jobs and my machine only has 32GB RAM

This does not matter since the program is not really using 9GB of physical memory.  You can use `/usr/bin/time` to print out the `maxresident` value to get the actual physical memory usage.  The rewritten binary should not be using significantly more than the original binary.

> I noticed that if the binaries were precompiled with -no-pie then the -m 9000 memory limit is sufficient!

Non-PIE forces the virtual address space layout to be more compact, which may explain the difference.

**Comment by passthecilantro** [comment]
Thank you for your thorough response and for providing a solution ! Your response kept me sane. Also thank you for the important citation !
