### ISSUE TITLE
C++ functionality in call instrumentation?

### ISSUE THREAD

**Issue by joshop** [GJDuck/e9patch#53]
Hi,
I'm using a C++ call instrumentation to patch a C++ program, and so far it hasn't exploded in my face yet. With that in mind:
- Are there any C++ things that are definitely not supported in call instrumentation for some reason or other?
- Is there a good way to interact with classes from the original program passed in via arguments? I've considered making parallel versions of all of those classes in my call instrumentation.
- If the original program uses some standard library classes like std::string or std::vector, how do I interact with those, seeing as there's no C++ standard library support and there's no parallel C++ library?
Just in general, what's the "intended" way to do this if there is one?

**Comment by GJDuck** [comment]
Basically any C++ functionality should work except for the stdlibc++ and any C++ features that implicitly invoke the stdlibc++ (like `new`, exceptions, etc.)

Interacting with `std::string` and `std::vector` is tricky since the implementation is mostly defined in header files, with some interaction with stdlibc++.  It would be necessary to reverse engineer the specific implementation used by the program, and engineer a way to modify it directly.
