### ISSUE TITLE
How to perform different actions depending on the return value of `e9patch_plugin_match` in call trampoline?

### ISSUE THREAD

**Issue by komorogrov** [GJDuck/e9patch#68]
Considering the following command line:

`./e9tool -M 'plugin(example).match()' -P 'entry()@count' ...`

Whether the return value of `e9_plugin_match` in the plugin code can be passed to the `entry` function of the count in the call trampoline, so that different operations can be performed in the `entry` function according to the match result of different instructions.

This is easy in plugin mode, just like example plugin do.

![deb-19](https://github.com/GJDuck/e9patch/assets/30967717/5f94b9a0-8b7f-4e2d-9f94-146328bb6e04)

However, because instrumentation is sometimes required to perform complex operations, it is too difficult to implement it entirely using assembly, so consider using call trampoline to achieve a similar effect.

**Comment by komorogrov** [comment]
The main case we want to consider is how can we execute different trampoline codes when different instructions are matched.

This means that **code A** is executed after matching the `call malloc` instruction and **code B** is executed after matching the `xor` instruction.


Instead of executing the same code at all instrumentation points, like `e9afl` or` counter`.

**Comment by GJDuck** [comment]
This should be possible with the following recipe:

        e9tool -M 'plugin(example).match() == 1' -P 'call1(...)@patch' \
               -M 'plugin(example).match() == 2' -P 'call2(...)@patch' \
               ...

Basically, the return value from `e9_plugin_match()` is passed directly to the matching script.  This will however call the plugin match function multiple times (once per `-M` option).

**Comment by komorogrov** [comment]
OK, thank you very much. This was a helpful answer and made me more familiar with how to use e9path.

**Comment by GJDuck** [comment]
No problem.

**Comment by komorogrov** [comment]
Is there any way to finish the above work in code nor command line?
This is because using the command line can be tedious in some complex situations, and you need to manually enumerate all the possibilities. 
It would be much more elegant and convenient if this could be done directly in code.
Is there any way to pass the return value from `e9_plugin_match()`  to the call trampoline code function `entry` instead of enumerating all the cases on the command line?

**Comment by GJDuck** [comment]
I think it should be possible since the API exists, although I do not think anyone has tested it, including myself.

In [e9tool.h](https://github.com/GJDuck/e9patch/blob/master/src/e9tool/e9tool.h), the relevant API calls are:

* `e9tool::sendCallTrampolineMessage`: Create a call trampoline template, which can be called from `e9_plugin_init()`.  You would need to figure out what all the arguments mean, probably by studying the source code.
* `e9tool::sendCallMetadata`: Instantiate the call trampoline for a given matching instruction, which can be called from `e9_plugn_patch()`.  Something like the code below:

```
extern void e9_plugin_code(const Context *cxt)
{
    fputs("\"$CALL\",", cxt->out);
}
extern void e9_plugin_patch(const Context *cxt)
{
    name = ... // Choose name of trampoline to call
    fprintf(cxt->out, "\"$CALL\":{\"rel32\":\"s\"},", name);
    e9tool::sendCallMetadata(cxt->out, name, ...);
}
```

It is probably easier to do it all from the command line.  It is possible to write a script to build and execute the E9Tool command you need.
