### ISSUE TITLE
A forward definition issue of the plugin mechanism

### ISSUE THREAD

**Issue by HQ1995** [GJDuck/e9patch#9]
I think some modifications related to the forward definition of the `struct ELF` need to be made. 

For example, when trying to dereference the `elf` parameter in the example, we cannot compile the plugin. 

```
/*
 * Initialize the counters and the trampoline.
 */
extern void *e9_plugin_init_v1(FILE *out, const e9frontend::ELF *elf)
{
    auto x = elf->free_addr;  <--- deref the elf parameter
    /* 
     * This example uses 3 counters (one for calls/jumps/returns).
```

```
clang++ -std=c++17 -fPIC -shared -o example.so -O2 examples/plugins/example.cpp -I . -I capstone/include
examples/plugins/example.cpp:57:17: error: member access into incomplete type 'const e9frontend::ELF'
    auto x = elf->free_addr;
                ^
./e9frontend.h:39:8: note: forward declaration of 'e9frontend::ELF'
struct ELF;
       ^
1 error generated.
```

**Comment by GJDuck** [comment]
The `struct ELF` type is intended to be opaque, since the layout will likely change in future versions.  For example, I'd like to store information about other sections, etc.  This will likely include API functions to access various members, but these functions have not been implemented yet.

As a stop-gap, you could copy the `struct ELF` definition into your plugin source file.  Just be careful when upgrading to newer versions of E9Tool/E9Patch that the layout has not changed.
