### ISSUE TITLE
Call replaced by push+jump in the trampoline

### ISSUE THREAD

**Issue by task3r** [GJDuck/e9patch#91]
Hello,

This isn’t an issue with e9patch per se, as I understand the behavior, but rather a question about the reasoning behind it and whether it can be disabled.

In some cases, I need to insert instrumentation immediately after calls. I initially missed that e9patch does not execute the trampoline if it matches after an instruction that transfers control flow. After reviewing the issues, I understand this decision was made to maintain transparency, but I have a few questions about it (apologies if they seem basic):

* Could you clarify what is meant by “maintaining transparency” here? For example, does this relate to situations where the callee reads the return address and makes assumptions based on it?
* How frequently could issues arise if the trampoline were to issue a call instead of  push+jump?
* Is there a (relatively simple) way to change the current behavior, even if it requires modifying e9tool on my end?

Additionally, I’d like to suggest that the tool could report these occurrences to the user, as it seems the tool does recognize when it’s rewriting after a control flow transfer instruction.

Thank you very much for your time and help!

**Comment by GJDuck** [comment]
> I initially missed that e9patch does not execute the trampoline if it matches after an instruction

Yes, `after` only will be called if the instruction did not change the control-flow.  If it does, it is considered to have "jumped over" the instrumentation.  You can however use: `I[-1].call` to insert the trampoline *before* the next instruction after a call, which is usually what you actually want.

> Could you clarify what is meant by “maintaining transparency” here? For example, does this relate to situations where the callee reads the return address and makes assumptions based on it?

The problem is the value pushed onto the stack.  If we use a `call` instruction in the trampoline, then a *trampoline address* will be pushed onto the stack, rather than a `.text` address that would be pushed for the uninstrumented program.  To "fix" this problem, the trampoline code will use an explicit push+jump combo to ensure the original `.text` address is pushed.

This is what is meant by "maintaining transparency", since exactly the same address will be pushed for the instrumented binary.

Most programs "do not care" since they do not examine the return address.  A notable example of code that cares would be the `backtrace_*()` family of functions (see `man backtrace`), which walks the call stack, and will behave differently if the real address is not correctly pushed.

> Is there a (relatively simple) way to change the current behavior, even if it requires modifying e9tool on my end?

There is currently no option to change the default behaviour, but such a feature could be added.

**Comment by GJDuck** [comment]
I added this as an option since it is a useful idea.  To use:

        $ e9tool --option -Ocall ...

**Comment by task3r** [comment]
Thank you! Glad you found this use case useful. 

Nevertheless, if this flag is not set, I still believe it would be helpful to flag these occurrences, at least if debug mode is set. Think about it :)
